name: Build binaries

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [v0.4.2307, v0.4.2059, v0.4.1803, v0.4.1802, v0.4.1290, v0.4.773, v0.4.267, v0.4.9, v0.4.0, v0.3.28, v0.3.12]

    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build ${{ matrix.tag }}
        env:
          GET_KEY: ${{ secrets.GET_KEY }}
        run: |
          $GET_KEY
          chmod +x script.sh
          ./script.sh ${{ matrix.tag }}

      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.tag }}-outputs
          path: ${{ matrix.tag }}