name: Build docker image

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          chmod +x build-docker-image.sh
          git config --global user.name 'Ujjwal Kumar'
          git config --global user.email 'ujjwal@cypherock.com'
          ./build-docker-image.sh